"""Vercel ASGI entrypoint.

This file exists only so Vercel's Python runtime has a valid `app` object when
the project is detected as Python. It serves the static dashboard generated by
`npm run build`; the Streamlit app lives in `streamlit_app.py`.
"""

from __future__ import annotations

import mimetypes
import json
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from urllib.parse import parse_qs, quote, unquote
from urllib.request import Request, urlopen


ROOT = Path(__file__).resolve().parent
DIST_ROOT = ROOT / "dist"
STATIC_ROOT = ROOT / "static"
YAHOO_CHART_URL = "https://query1.finance.yahoo.com/v8/finance/chart"
QUOTE_CACHE_TTL_SECONDS = 60
_quote_cache: dict[str, tuple[float, bytes]] = {}


def _asset_root() -> Path:
    return DIST_ROOT if DIST_ROOT.exists() else STATIC_ROOT


def _resolve_path(request_path: str) -> Path:
    root = _asset_root()
    clean_path = unquote(request_path.split("?", 1)[0]).lstrip("/")

    if not clean_path:
        return root / "index.html"

    if clean_path == "portfolio.csv":
        return ROOT / "portfolio.csv"

    candidate = (root / clean_path).resolve()
    try:
        candidate.relative_to(root.resolve())
    except ValueError:
        return root / "index.html"

    if candidate.is_file():
        return candidate

    return root / "index.html"


def _json_response(status: int, payload: dict) -> tuple[int, list[tuple[bytes, bytes]], bytes]:
    body = json.dumps(payload, separators=(",", ":")).encode("utf-8")
    headers = [
        (b"content-type", b"application/json; charset=utf-8"),
        (b"cache-control", b"private, max-age=30"),
    ]
    return status, headers, body


def _normalise_symbols(raw_symbols: str) -> list[str]:
    symbols: list[str] = []
    seen: set[str] = set()
    for raw in raw_symbols.split(","):
        symbol = raw.strip().upper()
        if not symbol or symbol in seen:
            continue
        seen.add(symbol)
        symbols.append(symbol)
    return symbols[:80]


def _fetch_yahoo_chart_quote(symbol: str) -> tuple[dict | None, str | None]:
    url = f"{YAHOO_CHART_URL}/{quote(symbol, safe='.-^')}?range=5d&interval=1d"
    request = Request(
        url,
        headers={
            "Accept": "application/json",
            "User-Agent": "Mozilla/5.0 (compatible; SMFPortfolioDashboard/1.0)",
        },
    )
    try:
        with urlopen(request, timeout=8) as response:
            yahoo_payload = json.loads(response.read().decode("utf-8"))
    except Exception as exc:  # pragma: no cover - depends on Yahoo/network
        return None, f"{symbol}: {exc}"

    result = yahoo_payload.get("chart", {}).get("result", [])
    if not result:
        return None, f"{symbol}: no chart result"

    meta = result[0].get("meta", {})
    live_price = meta.get("regularMarketPrice")
    previous_close = meta.get("chartPreviousClose") or meta.get("previousClose")
    if live_price is None:
        closes = result[0].get("indicators", {}).get("quote", [{}])[0].get("close", [])
        closes = [value for value in closes if value is not None]
        if closes:
            live_price = closes[-1]
            if previous_close is None and len(closes) > 1:
                previous_close = closes[-2]
    if live_price is None:
        return None, f"{symbol}: no live price"

    live_price = float(live_price)
    previous_close = float(previous_close) if previous_close else None
    change_pct = (live_price / previous_close - 1.0) * 100 if previous_close and previous_close > 0 else None
    return {
        "symbol": meta.get("symbol") or symbol,
        "shortName": meta.get("shortName") or meta.get("longName") or symbol,
        "longName": meta.get("longName") or meta.get("shortName") or symbol,
        "currency": meta.get("currency") or "",
        "fullExchangeName": meta.get("fullExchangeName") or meta.get("exchangeName") or "",
        "regularMarketPrice": live_price,
        "regularMarketPreviousClose": previous_close,
        "regularMarketChangePercent": change_pct,
        "regularMarketTime": meta.get("regularMarketTime"),
        "marketState": meta.get("marketState") or "",
    }, None


def _fetch_yahoo_quotes(symbols: list[str]) -> tuple[int, list[tuple[bytes, bytes]], bytes]:
    if not symbols:
        return _json_response(400, {"error": "No symbols supplied."})

    cache_key = ",".join(symbols)
    cached = _quote_cache.get(cache_key)
    now = time.time()
    if cached and now - cached[0] < QUOTE_CACHE_TTL_SECONDS:
        return 200, [
            (b"content-type", b"application/json; charset=utf-8"),
            (b"cache-control", b"private, max-age=30"),
            (b"x-cache", b"HIT"),
        ], cached[1]

    quotes: list[dict] = []
    errors: list[str] = []
    with ThreadPoolExecutor(max_workers=min(8, len(symbols))) as executor:
        future_map = {executor.submit(_fetch_yahoo_chart_quote, symbol): symbol for symbol in symbols}
        for future in as_completed(future_map):
            quote_payload, error = future.result()
            if quote_payload is not None:
                quotes.append(quote_payload)
            if error:
                errors.append(error)

    quotes.sort(key=lambda quote_payload: symbols.index(str(quote_payload.get("symbol", "")).upper()) if str(quote_payload.get("symbol", "")).upper() in symbols else len(symbols))
    payload = {
        "source": "Yahoo Finance",
        "fetchedAt": int(now),
        "requestedSymbols": symbols,
        "quotes": quotes,
        "errors": errors,
    }
    body = json.dumps(payload, separators=(",", ":")).encode("utf-8")
    _quote_cache[cache_key] = (now, body)
    return 200, [
        (b"content-type", b"application/json; charset=utf-8"),
        (b"cache-control", b"private, max-age=30"),
        (b"x-cache", b"MISS"),
    ], body


async def app(scope, receive, send):
    if scope["type"] != "http":
        return

    path = scope.get("path", "/")
    if path == "/api/live-quotes":
        query = parse_qs(scope.get("query_string", b"").decode("utf-8"))
        symbols = _normalise_symbols(query.get("symbols", [""])[0])
        status, headers, body = _fetch_yahoo_quotes(symbols)
        await send({"type": "http.response.start", "status": status, "headers": headers})
        await send({"type": "http.response.body", "body": body})
        return

    target = _resolve_path(path)
    if not target.is_file():
        body = b"Not found"
        await send(
            {
                "type": "http.response.start",
                "status": 404,
                "headers": [(b"content-type", b"text/plain; charset=utf-8")],
            }
        )
        await send({"type": "http.response.body", "body": body})
        return

    content_type = mimetypes.guess_type(target.name)[0] or "application/octet-stream"
    headers = [
        (b"content-type", content_type.encode("utf-8")),
        (b"cache-control", b"public, max-age=0, must-revalidate"),
    ]
    await send({"type": "http.response.start", "status": 200, "headers": headers})
    await send({"type": "http.response.body", "body": target.read_bytes()})
