"""Vercel ASGI entrypoint.

This file exists only so Vercel's Python runtime has a valid `app` object when
the project is detected as Python. It serves the static dashboard generated by
`npm run build`; the Streamlit app lives in `streamlit_app.py`.
"""

from __future__ import annotations

import mimetypes
from pathlib import Path
from urllib.parse import unquote


ROOT = Path(__file__).resolve().parent
DIST_ROOT = ROOT / "dist"
STATIC_ROOT = ROOT / "static"


def _asset_root() -> Path:
    return DIST_ROOT if DIST_ROOT.exists() else STATIC_ROOT


def _resolve_path(request_path: str) -> Path:
    root = _asset_root()
    clean_path = unquote(request_path.split("?", 1)[0]).lstrip("/")

    if not clean_path:
        return root / "index.html"

    if clean_path == "portfolio.csv":
        return ROOT / "portfolio.csv"

    candidate = (root / clean_path).resolve()
    try:
        candidate.relative_to(root.resolve())
    except ValueError:
        return root / "index.html"

    if candidate.is_file():
        return candidate

    return root / "index.html"


async def app(scope, receive, send):
    if scope["type"] != "http":
        return

    target = _resolve_path(scope.get("path", "/"))
    if not target.is_file():
        body = b"Not found"
        await send(
            {
                "type": "http.response.start",
                "status": 404,
                "headers": [(b"content-type", b"text/plain; charset=utf-8")],
            }
        )
        await send({"type": "http.response.body", "body": body})
        return

    content_type = mimetypes.guess_type(target.name)[0] or "application/octet-stream"
    headers = [
        (b"content-type", content_type.encode("utf-8")),
        (b"cache-control", b"public, max-age=0, must-revalidate"),
    ]
    await send({"type": "http.response.start", "status": 200, "headers": headers})
    await send({"type": "http.response.body", "body": target.read_bytes()})
